# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Construct < Formula
  desc "Your AI-powered development assistant"
  homepage "https://github.com/furisto/construct"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Furisto/construct/releases/download/v0.0.3/construct_0.0.3_darwin_amd64.tar.gz"
      sha256 "5bda26a92f2aafee9ebdb1d69f0277d815c76078aa29951071502d1705df4cc2"

      def install
        bin.install "construct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Furisto/construct/releases/download/v0.0.3/construct_0.0.3_darwin_arm64.tar.gz"
      sha256 "c6d00767f6ed01fdc83d4497eb81a8d1bda3b576f757aff189ef22634f341ab7"

      def install
        bin.install "construct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Furisto/construct/releases/download/v0.0.3/construct_0.0.3_linux_amd64.tar.gz"
      sha256 "0afcb8baa41429dadd666544f9ffe39236096cdef367c324bd4b50977708e650"
      def install
        bin.install "construct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Furisto/construct/releases/download/v0.0.3/construct_0.0.3_linux_arm64.tar.gz"
      sha256 "2209d65a11b4a44228310fff5e8611c7b604772301d9cac44557a54e9ff2700a"
      def install
        bin.install "construct"
      end
    end
  end

  test do
    system "#{bin}/construct", "version"
  end
end
