# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Construct < Formula
  desc "Your AI-powered development assistant"
  homepage "https://github.com/furisto/construct"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Furisto/construct/releases/download/v0.0.1/construct_0.0.1_darwin_amd64.tar.gz"
      sha256 "827ba2f3b6d1a252a1ef140605e66918b31c4d78463478b15c673052af2cde87"

      def install
        bin.install "construct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Furisto/construct/releases/download/v0.0.1/construct_0.0.1_darwin_arm64.tar.gz"
      sha256 "40e8dcfea052acae7c7cdc9010cf1aff280d1928a8597fc8adeb3935b72c66b5"

      def install
        bin.install "construct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Furisto/construct/releases/download/v0.0.1/construct_0.0.1_linux_amd64.tar.gz"
      sha256 "686620fcc0fe7448e347c1789ed6a73bdf53a7da28afb8d9665a83ef9e3dfe28"
      def install
        bin.install "construct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Furisto/construct/releases/download/v0.0.1/construct_0.0.1_linux_arm64.tar.gz"
      sha256 "41216321cce2923580f5ab804b14d383611acb4657da8e8f3625927e2b1d0630"
      def install
        bin.install "construct"
      end
    end
  end

  test do
    system "#{bin}/construct", "version"
  end
end
