# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Construct < Formula
  desc "Your AI-powered development assistant"
  homepage "https://github.com/furisto/construct"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Furisto/construct/releases/download/v0.0.8/darwin_amd64.tar.gz"
      sha256 "1a1210afe8e98ea52258e99bf0d072684a6092e940a3a927d3f72aab5c92587a"

      def install
        bin.install "construct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Furisto/construct/releases/download/v0.0.8/darwin_arm64.tar.gz"
      sha256 "73c4949aca493e757200d4e297db178b033b1954efd43df35485dd971e988ef2"

      def install
        bin.install "construct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Furisto/construct/releases/download/v0.0.8/linux_amd64.tar.gz"
      sha256 "355b6d7018898654753cdf0e374c9b773f7be4f3745f68c093a32d5837f30076"
      def install
        bin.install "construct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Furisto/construct/releases/download/v0.0.8/linux_arm64.tar.gz"
      sha256 "ff2b00d5724baf3fc344afd065d6fdc50e5ae8ba22f833803f0fbc73d276a207"
      def install
        bin.install "construct"
      end
    end
  end

  test do
    system "#{bin}/construct", "version"
  end
end
